Feature/multi label select
CentreForDigitalHumanities/lettercraft pull request #110
Opened 2024-08-09 09:28 UTC by XanderVertegaal

This PR adds two components, both implementing the ControlValueAccessor, both added to the 
- a general MultiSelect (dropdown) component that we might be able to reuse in the future;
- a specific LabelSelectComponent that uses the MultiSelectComponent under the hood.

For easy functional testing I suggest adding the code below to any component (e.g. the HomeComponent).

One issue I could use your help on is making the control keyboard navigable. I got it to the point where I can cycle through options using the arrow keys (apparently adding a `hidden` attribute breaks this, which is why I had to use classes instead), but I did not manage to get a `keydown` event to work on any of the options.

HTML
```html
<lc-label-select [options]="options" [formControl]="control" />
```

TS
```ts
    control = new FormControl<string[]>([]);
    options: MultiselectItem[] = [
        {
            id: "1",
            label: "Writing",
        },
        {
            id: "2",
            label: "Reading",
        },
        {
            id: "3",
            label: "Sending",
        },
        {
            id: "4",
            label: "Licking",
        },
    ];
```

2024-08-13 14:03 UTC, lukavdplas requested changes

2024-08-14 13:26 UTC, XanderVertegaal commented on frontend/src/app/data-entry/shared/multiselect/multiselect.component.html
> +</select>
ngbDropdown is just the component I need <3 Thanks for pointing this out!

2024-08-16 09:12 UTC, XanderVertegaal commented
Thanks for your comments! I think I have all of them now :) This is now a much better widget than it was before!

2024-08-20 13:06 UTC, lukavdplas approved these changes

2024-08-20 14:06 UTC, merged