Feature/episode order
CentreForDigitalHumanities/lettercraft pull request #154
Opened 2024-10-25 10:47 UTC by XanderVertegaal

Closes #122 

Adds a `rank` property to objects inheriting EntityDescription and allows the user to drag/drop episodes in a source's episode overview to reorder them (using Angular Material's CDK).

I'd be happy to discuss alternatives if you think rank-based ordering or a drag-and-drop interface are not the way to go.

2024-10-28 13:38 UTC, XanderVertegaal commented
This PR will be adjusted to replace the drag and drop interface with buttons to move episodes 'up'/'down' in the hierarchy.

2024-10-29 11:02 UTC, lukavdplas requested changes
For clarity, the point about the drag-and-drop UI was something we discussed outside of Github.

I added some additional comments on the backend. These are smaller suggestions, but please take a look at those as well.

2024-10-29 11:02 UTC, lukavdplas commented on backend/event/mutations/UpdateEpisodeOrderMutation.py
> +        }
I think these type declarations need to be `List` and `Dict` instead of `list` and `dict`, right?

2024-10-30 15:41 UTC, XanderVertegaal commented
I will reopen another PR with `order_with_respect_to` and with a new interface.

2024-10-30 15:41 UTC, closed without merging