Feature/source description split
CentreForDigitalHumanities/lettercraft pull request #45
Opened 2024-03-24 12:34 UTC by XanderVertegaal

This PR introduces a split between actual, 'historical' entities and source descriptions. The implementation is as follows.

There are two abstract models, as per your suggestion:
- `Historical` is an empty abstract class. It marks historical entities and we can use it to later implement fields that are common to all of them, if needed.
- `SourceDescription` contains fields that used to be in the `Reference` model and is inherited by source description models. As far as I can see, this class now renders the `Reference` model obsolete, so I removed it.

The idea is that each entity is represented by three model objects (taking `Agent` as an example).
 - `Agent` inherits from `Historical` and represents the actual 'aggregated' historical entity in our knowledge base. (We need a better term for this 😅).
 - `AgentDescription` inherits from `AgentBase` and `SourceDescription` and includes a `target` field that links it to the `Agent`. This replaces the `GenericForeignKey` that existed on the `Reference` model.
 -  `AgentBase` is the base model that contains all the relevant fields (`names`, `gender`, `is_group` etc.). The end user should not have to deal with this, and it has not been included in the Django admin interface.

In the `AgentDescription` admin interface, we can easily select a target for a description:
![image](https://github.com/CentreForDigitalHumanities/lettercraft/assets/73882506/58805e9b-0d16-41a2-963f-13ef5454dfbe)

In the `Agent` admin interface, connected descriptions are shown in a tabular inline.
![image](https://github.com/CentreForDigitalHumanities/lettercraft/assets/73882506/9b26183b-6c10-4856-a0de-8d385a255ebe)

2024-04-02 11:41 UTC, lukavdplas requested changes
Your code looks good as always, but the way the models are divided is not quite what I had in mind. I've added my thoughts here, but if you prefer, we can also discuss in person what we want to do.

2024-04-02 11:41 UTC, lukavdplas commented on backend/event/models.py
> +    """
I'm not sure if there is any need for the "historical" letter action. In the case of agents, it makes sense that a description of an individual in a source will often correspond to a known historical figure, and that these historical figures are a useful "entry point" into the database. Cross-referencing individual actions is much harder, if ever possible, and less useful for making queries.

I would argue that while a `SourceDescription` is often referring to something "real" (e.g. a person, an action, a place), it's not always useful to represent both layers in the database, if they don't serve the analysis. (In the case of actions, it is also tricky that actions in texts do not necessarily represent "real" events but may serve a literary purpose.)

2024-04-02 11:41 UTC, lukavdplas commented on backend/person/models.py
> +class AgentDescription(SourceDescription, AgentBase):
This is also applies to other models. In most cases, information that is represented in the `SourceDescription` does not need to be duplicated in the corresponding `Historical` model. It's more precise to display or query the agent through its descriptions.

I would say that an `Agent` may also include information of its own, but mainly things that are not really connected to sources, and more about representing the agent in the interface.

For example, the `Agent` Radegund could include a name, longer description, and an image that can be used in the interface. Then an `AgentDescription` of Radegund describes the language used in source texts to describe her gender, social status, names used in the text, etc.

2024-04-02 11:41 UTC, lukavdplas commented on backend/letter/models.py
> +class Gift(Historical, GiftBase, models.Model):
Same thing as for actions: I think we can start out without a `Historical` model for gifts and letters, though we can add that layer of analysis when needed.

2024-04-02 11:41 UTC, lukavdplas commented on backend/space/models.py
> +    """
"A description of a space description"?

This distinction is not really appropriate here; as this awkward docstring highlights, `SpaceDescription` was already a type of description.

In the case of spaces, as I understand it, source texts are so different in what they describe, and so vague, that it is a futile exercise to try to link specific places between sources. This is why we ended up with a model where a single `SpaceDescription` contains several _aspects_ that may have been described, each of which may link to a historical reference point, such as a kingdom or diocese.

So to map the `space` app to the `Historical`/`Description` division... When I wrote this originally, I imagined we would divide it like this:
- `PoliticalRegion`, `EcclesiasticalRegion`, etc., are all `Historical` models
- `SpaceDescription` is a `SourceDescription`

2024-04-04 07:46 UTC, XanderVertegaal commented
Alright, it does seem I have misunderstood a couple of things; let's discuss the necessary refactors soon!

2024-04-12 07:53 UTC, closed without merging